"use client";
import { useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, Bot, FlaskConical, Gauge, Pause, Play, RotateCcw, TestTube2, Wifi } from "lucide-react";
type Workload={experiment:string;sample:string;slot:string;state:string;progress:number};
type Device={id:string;name:string;type:string;state:"运行中"|"空闲"|"异常";action:string;progress:number;detail:string;mode:"独占"|"容量并发";capacity:number;workloads:Workload[]};
const devices:Device[]=[
{id:"robot-01",name:"移动机器人 01",type:"RobotControl",state:"运行中",action:"搬运 plate-001 至检测设备",progress:64,detail:"位于通道 B，载荷 1 个孔板",mode:"独占",capacity:1,workloads:[{experiment:"EXP-2026-014",sample:"plate-001",slot:"载台",state:"搬运中",progress:64}]},
{id:"liquid-01",name:"液体处理器 01",type:"LiquidHandling",state:"空闲",action:"等待下一任务",progress:0,detail:"枪头 72%，台面已清洁",mode:"独占",capacity:1,workloads:[]},
{id:"reader-01",name:"微孔板检测仪 01",type:"Measurement",state:"异常",action:"等待操作员确认",progress:38,detail:"舱门未关闭，检测已暂停",mode:"独占",capacity:1,workloads:[{experiment:"EXP-2026-009",sample:"plate-009",slot:"读板舱",state:"异常暂停",progress:38}]},
{id:"incubator-01",name:"恒温培养设备 01",type:"Incubation",state:"运行中",action:"3 个实验并发培养",progress:58,detail:"37.0 °C，CO₂ 5.0%，三个槽位独立计时",mode:"容量并发",capacity:8,workloads:[{experiment:"EXP-2026-014",sample:"plate-002",slot:"槽位 A1",state:"培养中",progress:72},{experiment:"EXP-2026-021",sample:"plate-017",slot:"槽位 A2",state:"培养中",progress:46},{experiment:"EXP-2026-023",sample:"plate-022",slot:"槽位 B1",state:"培养中",progress:19}]}];
const initialEvents=[["14:32:18","机器人","已到达设备交接点 B","ok"],["14:32:12","工作流","步骤 3 搬运开始","info"],["14:31:54","检测仪","告警：舱门未关闭","error"],["14:31:48","液体处理","稀释步骤完成","ok"],["14:31:03","Agent","实验计划通过确定性验证","info"]];
const experimentRuns=[
 {id:"EXP-2026-014",name:"板式稀释与吸光度检测",device:"培养设备 · A1",eta:"14:38",active:3,steps:["任务验证","孔板准备","液体稀释","恒温培养","机器人搬运","吸光度检测"]},
 {id:"EXP-2026-021",name:"细胞活性筛选",device:"培养设备 · A2",eta:"14:51",active:2,steps:["任务验证","样品装载","恒温培养","荧光检测","结果归档"]},
 {id:"EXP-2026-023",name:"培养条件探索",device:"培养设备 · B1",eta:"15:06",active:1,steps:["任务验证","恒温培养","图像采集","质量检查","结果归档"]}
];
function Status({state}:{state:Device["state"]}){return <span className={`status status-${state}`}>● {state}</span>}
export default function Home(){
 const[selected,setSelected]=useState<Device>(devices[0]);const[running,setRunning]=useState(true);const[robotX,setRobotX]=useState(49);const[events,setEvents]=useState(initialEvents);
 useEffect(()=>{if(!running)return;const t=window.setInterval(()=>setRobotX(x=>x>=72?35:x+.7),120);return()=>window.clearInterval(t)},[running]);
 const eta=useMemo(()=>Math.max(1,Math.round((76-robotX)/2.6)),[robotX]);
 function injectFault(){setEvents(old=>[[new Date().toLocaleTimeString("zh-CN",{hour12:false}),"模拟器","注入故障：机器人路径被占用","error"],...old].slice(0,7));setRunning(false)}
 return <main className="app-shell">
  <header className="topbar"><div className="brand"><span className="brand-mark"><FlaskConical size={19}/></span><div><strong>LabFlow Twin</strong><small>探索性实验室 Demo</small></div></div><div className="run-summary"><span className="live-dot"/> 实验 EXP-2026-014 正在运行 <b>4 / 7 步</b></div><div className="top-actions"><button className="ghost" onClick={()=>setRunning(!running)}>{running?<Pause size={16}/>:<Play size={16}/>} {running?"暂停演示":"继续演示"}</button><button className="danger" onClick={injectFault}><AlertTriangle size={16}/> 注入异常</button></div></header>
  <section className="metrics" aria-label="实验室状态"><div><span>设备在线</span><strong>4 / 4</strong><small><Wifi size={13}/> SiLA 2 连接正常</small></div><div><span>当前实验</span><strong>3</strong><small><Activity size={13}/> 培养设备并发承载 3 个实验</small></div><div><span>机器人任务</span><strong>{running?"搬运中":"已暂停"}</strong><small><Bot size={13}/> ETA {eta} 秒</small></div><div className="metric-alert"><span>活动告警</span><strong>1</strong><small><AlertTriangle size={13}/> 检测仪舱门</small></div></section>
  <section className="workspace"><div className="map-panel"><div className="panel-heading"><div><h1>设备孪生地图</h1><p>实验室 A · 数据延迟 180 ms</p></div><div className="legend"><span><i className="lg online"/>在线</span><span><i className="lg busy"/>运行</span><span><i className="lg alarm"/>异常</span></div></div>
   <div className="lab-map"><div className="map-stage"><svg viewBox="0 0 900 510" role="img" aria-label="实验室布局图"><defs><pattern id="grid" width="28" height="28" patternUnits="userSpaceOnUse"><path d="M28 0L0 0 0 28" className="grid-line"/></pattern></defs><rect width="900" height="510" rx="16" className="map-bg"/><rect width="900" height="510" rx="16" fill="url(#grid)"/><path d="M126 260H725" className="robot-path"/><path d="M360 120V390" className="robot-path faint"/>
   <g className="station" onClick={()=>setSelected(devices[1])}><rect x="55" y="78" width="220" height="135" rx="14"/><text x="75" y="110">液体处理设备</text><text x="75" y="140" className="machine-label">Liquid Handler 01</text><circle cx="245" cy="103" r="6" className="dot-idle"/><rect x="82" y="160" width="64" height="30" rx="5" className="plate"/><text x="91" y="180" className="plate-label">plate-001</text></g>
   <g className="station alarm-station" onClick={()=>setSelected(devices[2])}><rect x="625" y="72" width="220" height="145" rx="14"/><text x="647" y="105">检测设备</text><text x="647" y="136" className="machine-label">Plate Reader 01</text><circle cx="815" cy="100" r="6" className="dot-alarm"/><path d="M760 160l10-18 10 18z" className="alarm-symbol"/></g>
   <g className="station multi-station" onClick={()=>setSelected(devices[3])}><rect x="50" y="330" width="220" height="120" rx="14"/><text x="72" y="363">恒温培养设备</text><text x="72" y="390" className="machine-label">Incubator 01 · 3 / 8 槽位</text><text x="72" y="416" className="multi-label">EXP-014 · EXP-021 · EXP-023</text><circle cx="240" cy="357" r="6" className="dot-running"/></g><g className="station"><rect x="625" y="330" width="220" height="120" rx="14"/><text x="647" y="363">机器人充电设备</text><text x="647" y="392" className="machine-label">Dock 01 · Ready</text></g>
   <g className="robot" transform={`translate(${robotX*8.3},260)`} onClick={()=>setSelected(devices[0])}><circle r="28"/><circle r="20" className="robot-inner"/><path d="M-10-3h20M-7 7h14"/><circle cx="-9" cy="-10" r="2.5"/><circle cx="9" cy="-10" r="2.5"/><text x="0" y="48" textAnchor="middle">Robot 01</text></g><g className="zone"><rect x="410" y="184" width="112" height="54" rx="10"/><text x="466" y="207" textAnchor="middle">互斥区 B</text><text x="466" y="225" textAnchor="middle" className="zone-status">Robot 01 占用</text></g></svg><div className="map-toast"><Bot size={16}/><span><b>Robot 01</b> 搬运 plate-001</span><em>{Math.round(robotX)}%</em></div></div></div></div>
   <aside className="device-panel"><div className="panel-heading"><div><h2>设备状态</h2><p>点击设备查看详情</p></div></div><div className="device-list">{devices.map(d=><button key={d.id} className={`device-card ${selected.id===d.id?"selected":""}`} onClick={()=>setSelected(d)}><div className="device-title"><span className="device-icon">{d.id.startsWith("robot")?<Bot/>:d.id.startsWith("liquid")?<TestTube2/>:<Gauge/>}</span><div><b>{d.name}</b><small>{d.type}</small></div><Status state={d.state}/></div><p>{d.action}</p><div className="capacity-line"><span>{d.mode}</span><b>{d.workloads.length} / {d.capacity} 占用</b></div>{d.progress>0&&<div className="progress"><span style={{width:`${d.progress}%`}}/></div>}</button>)}</div><div className="detail-card"><div className="detail-head"><div><small>当前选择</small><h3>{selected.name}</h3></div><Status state={selected.state}/></div><p>{selected.detail}</p><dl><div><dt>并发模式</dt><dd>{selected.mode}</dd></div><div><dt>资源占用</dt><dd>{selected.workloads.length} / {selected.capacity}</dd></div><div><dt>Feature</dt><dd>{selected.type}</dd></div></dl>{selected.workloads.length>0&&<div className="workloads"><small>设备内运行实验</small>{selected.workloads.map(w=><div className="workload" key={`${w.experiment}-${w.slot}`}><div><b>{w.experiment}</b><span>{w.sample} · {w.slot}</span></div><em>{w.state} {w.progress}%</em></div>)}</div>}<button className="secondary"><RotateCcw size={15}/> 查看事件历史</button></div></aside></section>
  <section className="bottom-grid"><div className="run-panel"><div className="panel-heading"><div><h2>并行实验执行链</h2><p>3 个实验正在共享设备资源</p></div><span className="eta">3 RUNNING</span></div><div className="experiment-runs">{experimentRuns.map(run=><div className="experiment-run" key={run.id}><div className="run-identity"><b>{run.id}</b><span>{run.name}</span><small>{run.device} · ETA {run.eta}</small></div><div className="mini-steps">{run.steps.map((s,i)=><div key={s} className={`mini-step ${i<run.active?"done":i===run.active?"active":""}`} title={s}><i>{i<run.active?"✓":i+1}</i><span>{s}</span>{i<run.steps.length-1&&<b/>}</div>)}</div></div>)}</div></div><div className="event-panel"><div className="panel-heading"><div><h2>实时事件</h2><p>命令、状态与异常回流</p></div></div><div className="events">{events.map((e,i)=><div className={`event ${e[3]}`} key={`${e[0]}-${i}`}><time>{e[0]}</time><b>{e[1]}</b><span>{e[2]}</span></div>)}</div></div></section>
 </main>
}
