"use client";
import { useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, Bot, FlaskConical, Gauge, Pause, Play, RotateCcw, TestTube2, Wifi } from "lucide-react";
type Device={id:string;name:string;type:string;state:"运行中"|"空闲"|"异常";action:string;progress:number;detail:string};
const devices:Device[]=[
{id:"robot-01",name:"移动机器人 01",type:"RobotControl",state:"运行中",action:"搬运 plate-001 至检测工位",progress:64,detail:"位于通道 B，载荷 1 个孔板"},
{id:"liquid-01",name:"液体处理器 01",type:"LiquidHandling",state:"空闲",action:"等待下一任务",progress:0,detail:"枪头 72%，台面已清洁"},
{id:"reader-01",name:"微孔板检测仪 01",type:"Measurement",state:"异常",action:"等待操作员确认",progress:38,detail:"舱门未关闭，检测已暂停"}];
const initialEvents=[["14:32:18","机器人","已到达中转工位 B","ok"],["14:32:12","工作流","步骤 3 搬运开始","info"],["14:31:54","检测仪","告警：舱门未关闭","error"],["14:31:48","液体处理","稀释步骤完成","ok"],["14:31:03","Agent","实验计划通过确定性验证","info"]];
function Status({state}:{state:Device["state"]}){return <span className={`status status-${state}`}>● {state}</span>}
export default function Home(){
 const[selected,setSelected]=useState<Device>(devices[0]);const[running,setRunning]=useState(true);const[robotX,setRobotX]=useState(49);const[events,setEvents]=useState(initialEvents);
 useEffect(()=>{if(!running)return;const t=window.setInterval(()=>setRobotX(x=>x>=72?35:x+.7),120);return()=>window.clearInterval(t)},[running]);
 const eta=useMemo(()=>Math.max(1,Math.round((76-robotX)/2.6)),[robotX]);
 function injectFault(){setEvents(old=>[[new Date().toLocaleTimeString("zh-CN",{hour12:false}),"模拟器","注入故障：机器人路径被占用","error"],...old].slice(0,7));setRunning(false)}
 return <main className="app-shell">
  <header className="topbar"><div className="brand"><span className="brand-mark"><FlaskConical size={19}/></span><div><strong>LabFlow Twin</strong><small>探索性实验室 Demo</small></div></div><div className="run-summary"><span className="live-dot"/> 实验 EXP-2026-014 正在运行 <b>4 / 7 步</b></div><div className="top-actions"><button className="ghost" onClick={()=>setRunning(!running)}>{running?<Pause size={16}/>:<Play size={16}/>} {running?"暂停演示":"继续演示"}</button><button className="danger" onClick={injectFault}><AlertTriangle size={16}/> 注入异常</button></div></header>
  <section className="metrics" aria-label="实验室状态"><div><span>设备在线</span><strong>3 / 3</strong><small><Wifi size={13}/> SiLA 2 连接正常</small></div><div><span>当前实验</span><strong>1</strong><small><Activity size={13}/> 预计 6 分钟完成</small></div><div><span>机器人任务</span><strong>{running?"搬运中":"已暂停"}</strong><small><Bot size={13}/> ETA {eta} 秒</small></div><div className="metric-alert"><span>活动告警</span><strong>1</strong><small><AlertTriangle size={13}/> 检测仪舱门</small></div></section>
  <section className="workspace"><div className="map-panel"><div className="panel-heading"><div><h1>设备孪生地图</h1><p>实验室 A · 数据延迟 180 ms</p></div><div className="legend"><span><i className="lg online"/>在线</span><span><i className="lg busy"/>运行</span><span><i className="lg alarm"/>异常</span></div></div>
   <div className="lab-map"><svg viewBox="0 0 900 510" role="img" aria-label="实验室布局图"><defs><pattern id="grid" width="28" height="28" patternUnits="userSpaceOnUse"><path d="M28 0L0 0 0 28" className="grid-line"/></pattern></defs><rect width="900" height="510" rx="16" className="map-bg"/><rect width="900" height="510" rx="16" fill="url(#grid)"/><path d="M126 260H725" className="robot-path"/><path d="M360 120V390" className="robot-path faint"/>
   <g className="station" onClick={()=>setSelected(devices[1])}><rect x="55" y="78" width="220" height="135" rx="14"/><text x="75" y="110">液体处理工位</text><text x="75" y="140" className="machine-label">Liquid Handler 01</text><circle cx="245" cy="103" r="6" className="dot-idle"/><rect x="82" y="160" width="64" height="30" rx="5" className="plate"/><text x="91" y="180" className="plate-label">plate-001</text></g>
   <g className="station alarm-station" onClick={()=>setSelected(devices[2])}><rect x="625" y="72" width="220" height="145" rx="14"/><text x="647" y="105">检测工位</text><text x="647" y="136" className="machine-label">Plate Reader 01</text><circle cx="815" cy="100" r="6" className="dot-alarm"/><path d="M760 160l10-18 10 18z" className="alarm-symbol"/></g>
   <g className="station"><rect x="50" y="330" width="220" height="120" rx="14"/><text x="72" y="363">样品暂存区</text><text x="72" y="392" className="machine-label">Station A · 2 / 8</text></g><g className="station"><rect x="625" y="330" width="220" height="120" rx="14"/><text x="647" y="363">机器人充电区</text><text x="647" y="392" className="machine-label">Dock 01 · Ready</text></g>
   <g className="robot" transform={`translate(${robotX*8.3},260)`} onClick={()=>setSelected(devices[0])}><circle r="28"/><circle r="20" className="robot-inner"/><path d="M-10-3h20M-7 7h14"/><circle cx="-9" cy="-10" r="2.5"/><circle cx="9" cy="-10" r="2.5"/><text x="0" y="48" textAnchor="middle">Robot 01</text></g><g className="zone"><rect x="330" y="224" width="112" height="72" rx="12"/><text x="386" y="254" textAnchor="middle">互斥区 B</text><text x="386" y="276" textAnchor="middle" className="zone-status">已占用</text></g></svg><div className="map-toast"><Bot size={16}/><span><b>Robot 01</b> 搬运 plate-001</span><em>{Math.round(robotX)}%</em></div></div></div>
   <aside className="device-panel"><div className="panel-heading"><div><h2>设备状态</h2><p>点击设备查看详情</p></div></div><div className="device-list">{devices.map(d=><button key={d.id} className={`device-card ${selected.id===d.id?"selected":""}`} onClick={()=>setSelected(d)}><div className="device-title"><span className="device-icon">{d.id.startsWith("robot")?<Bot/>:d.id.startsWith("liquid")?<TestTube2/>:<Gauge/>}</span><div><b>{d.name}</b><small>{d.type}</small></div><Status state={d.state}/></div><p>{d.action}</p>{d.progress>0&&<div className="progress"><span style={{width:`${d.progress}%`}}/></div>}</button>)}</div><div className="detail-card"><div className="detail-head"><div><small>当前选择</small><h3>{selected.name}</h3></div><Status state={selected.state}/></div><p>{selected.detail}</p><dl><div><dt>当前动作</dt><dd>{selected.action}</dd></div><div><dt>Feature</dt><dd>{selected.type}</dd></div><div><dt>状态新鲜度</dt><dd>180 ms</dd></div></dl><button className="secondary"><RotateCcw size={15}/> 查看事件历史</button></div></aside></section>
  <section className="bottom-grid"><div className="run-panel"><div className="panel-heading"><div><h2>实验执行链</h2><p>EXP-2026-014 · 板式稀释与吸光度检测</p></div><span className="eta">预计完成 14:38</span></div><div className="steps">{["任务验证","孔板准备","液体稀释","机器人搬运","吸光度检测","结果归档"].map((s,i)=><div key={s} className={`step ${i<3?"done":i===3?"active":i===4?"blocked":""}`}><i>{i<3?"✓":i+1}</i><span>{s}</span>{i<5&&<b/>}</div>)}</div></div><div className="event-panel"><div className="panel-heading"><div><h2>实时事件</h2><p>命令、状态与异常回流</p></div></div><div className="events">{events.map((e,i)=><div className={`event ${e[3]}`} key={`${e[0]}-${i}`}><time>{e[0]}</time><b>{e[1]}</b><span>{e[2]}</span></div>)}</div></div></section>
 </main>
}
