"use client";
import { useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, Bot, FlaskConical, Gauge, ListTree, Minus, Pause, Play, Plus, RotateCcw, Server, TestTube2, Wifi } from "lucide-react";
import { Sheet, SheetClose, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
type Workload={experiment:string;sample:string;slot:string;state:string;progress:number};
type Device={id:string;name:string;type:string;state:"运行中"|"空闲"|"异常";action:string;progress:number;detail:string;mode:"独占"|"容量并发"|"批处理";capacity:number;workloads:Workload[]};
const devices:Device[]=[
{id:"robot-01",name:"移动机器人 01",type:"RobotControl",state:"运行中",action:"搬运 plate-001 至检测设备",progress:64,detail:"位于通道 B，载荷 1 个孔板",mode:"独占",capacity:1,workloads:[{experiment:"EXP-2026-014",sample:"plate-001",slot:"载台",state:"搬运中",progress:64}]},
{id:"liquid-01",name:"液体处理器 01",type:"LiquidHandling",state:"空闲",action:"等待下一任务",progress:0,detail:"枪头 72%，台面已清洁",mode:"独占",capacity:1,workloads:[]},
{id:"reader-01",name:"微孔板检测仪 01",type:"Measurement",state:"异常",action:"等待设备侧自检恢复",progress:38,detail:"舱门未关闭，检测已暂停；平台等待设备人员处理",mode:"独占",capacity:1,workloads:[{experiment:"EXP-2026-009",sample:"plate-009",slot:"读板舱",state:"异常暂停",progress:38}]},
{id:"incubator-01",name:"恒温培养设备 01",type:"Incubation",state:"运行中",action:"3 个实验并发培养",progress:58,detail:"37.0 °C，CO₂ 5.0%，三个槽位独立计时",mode:"容量并发",capacity:8,workloads:[{experiment:"EXP-2026-014",sample:"plate-002",slot:"槽位 A1",state:"培养中",progress:72},{experiment:"EXP-2026-021",sample:"plate-017",slot:"槽位 A2",state:"培养中",progress:46},{experiment:"EXP-2026-023",sample:"plate-022",slot:"槽位 B1",state:"培养中",progress:19}]},
{id:"centrifuge-01",name:"离心设备 01",type:"Centrifugation",state:"空闲",action:"转子已平衡，等待任务",progress:0,detail:"转子容量 8，舱盖锁定正常",mode:"批处理",capacity:8,workloads:[]},
{id:"imager-01",name:"显微成像设备 01",type:"Imaging",state:"运行中",action:"采集 EXP-2026-021 图像",progress:31,detail:"20× 物镜，通道 GFP，正在扫描视野 4 / 12",mode:"独占",capacity:1,workloads:[{experiment:"EXP-2026-021",sample:"plate-018",slot:"成像台",state:"采集中",progress:31}]}];
const initialEvents=[["14:32:18","机器人","已到达设备交接点 B","ok"],["14:32:12","工作流","步骤 3 搬运开始","info"],["14:31:54","检测仪","告警：舱门未关闭，等待设备侧处理与自检","error"],["14:31:48","液体处理","稀释步骤完成","ok"],["14:31:03","Agent","实验计划通过确定性验证","info"]];
const experimentRuns=[
 {id:"EXP-2026-014",name:"板式稀释与吸光度检测",device:"培养设备 · A1",eta:"14:38",active:3,steps:["任务验证","孔板准备","液体稀释","恒温培养","机器人搬运","吸光度检测"]},
 {id:"EXP-2026-021",name:"细胞活性筛选",device:"培养设备 · A2",eta:"14:51",active:2,steps:["任务验证","样品装载","恒温培养","荧光检测","结果归档"]},
 {id:"EXP-2026-023",name:"培养条件探索",device:"培养设备 · B1",eta:"15:06",active:1,steps:["任务验证","恒温培养","图像采集","质量检查","结果归档"]}
];
type RouteStatus="done"|"current"|"upcoming";
const experimentRoutes={
 "EXP-2026-014":[{deviceId:"liquid-01",status:"done"},{deviceId:"incubator-01",status:"current"},{deviceId:"robot-01",status:"upcoming"},{deviceId:"reader-01",status:"upcoming"}],
 "EXP-2026-021":[{deviceId:"incubator-01",status:"done"},{deviceId:"imager-01",status:"current"},{deviceId:"reader-01",status:"upcoming"}],
 "EXP-2026-023":[{deviceId:"liquid-01",status:"done"},{deviceId:"centrifuge-01",status:"current"},{deviceId:"incubator-01",status:"upcoming"},{deviceId:"imager-01",status:"upcoming"}]
} satisfies Record<string,{deviceId:string;status:RouteStatus}[]>;
function Status({state}:{state:Device["state"]}){return <span className={`status status-${state}`}>● {state}</span>}
export default function Home(){
 const[selected,setSelected]=useState<Device>(devices[0]);const[running,setRunning]=useState(true);const[robotX,setRobotX]=useState(49);const[events,setEvents]=useState(initialEvents);const[zoom,setZoom]=useState(1);const[selectedExperiment,setSelectedExperiment]=useState<keyof typeof experimentRoutes>("EXP-2026-014");
 useEffect(()=>{if(!running)return;const t=window.setInterval(()=>setRobotX(x=>x>=72?35:x+.7),120);return()=>window.clearInterval(t)},[running]);
 const eta=useMemo(()=>Math.max(1,Math.round((76-robotX)/2.6)),[robotX]);
 const route=useMemo(()=>experimentRoutes[selectedExperiment].map(node=>({...node,point:node.deviceId==="liquid-01"?[165,145]:node.deviceId==="reader-01"?[735,145]:node.deviceId==="incubator-01"?[160,390]:node.deviceId==="centrifuge-01"?[450,121]:node.deviceId==="imager-01"?[450,395]:[robotX*8.3,260]})),[selectedExperiment,robotX]);
 const routeStatus=(deviceId:string)=>route.find(node=>node.deviceId===deviceId)?.status;
 function injectFault(){setEvents(old=>[[new Date().toLocaleTimeString("zh-CN",{hour12:false}),"模拟器","注入故障：机器人路径被占用","error"],...old].slice(0,7));setRunning(false)}
 return <main className="app-shell lab-overview">
  <header className="topbar"><div className="brand"><span className="brand-mark"><FlaskConical size={19}/></span><div><strong>LabFlow Twin</strong><small>实验室 A</small></div></div><nav className="page-nav"><a className="active" href="/">实验室总览</a><a href="/experiments">实验列表</a></nav><div className="top-actions"><button className="ghost" onClick={()=>setRunning(!running)}>{running?<Pause size={16}/>:<Play size={16}/>} {running?"暂停演示":"继续演示"}</button><button className="danger" onClick={injectFault}><AlertTriangle size={16}/> 注入异常</button></div></header>
  <section className="metrics environment-metrics" aria-label="实验室环境状态"><div><span>设备在线</span><strong>6 / 6</strong><small><Wifi size={13}/> SiLA 2 连接正常</small></div><div><span>温度 / 湿度</span><strong>22.4°C</strong><small><Activity size={13}/> 45% RH · 稳定</small></div><div><span>气压 / 空气</span><strong>101.2 kPa</strong><small><Activity size={13}/> PM2.5 3 μg/m³</small></div><div className="metric-alert"><span>活动告警</span><strong>1</strong><small><AlertTriangle size={13}/> 检测仪舱门</small></div></section>
  <section className="workspace"><div className="map-panel"><div className="panel-heading map-heading"><div><small className="eyebrow">LIVE DEVICE MAP</small><h1>实验室实时设备地图</h1><p>实验室 A · 6 台设备在线 · 数据延迟 180 ms</p></div><div className="legend"><span><i className="lg online"/>在线</span><span><i className="lg busy"/>运行</span><span><i className="lg alarm"/>异常</span></div></div>
   <div className="lab-map"><div className="map-stage" onWheel={e=>setZoom(z=>Math.min(1.5,Math.max(.7,+(z+(e.deltaY<0?.1:-.1)).toFixed(1))))}><svg style={{transform:`scale(${zoom})`}} viewBox="0 0 900 510" role="img" aria-label="实验室布局图"><defs><pattern id="grid" width="28" height="28" patternUnits="userSpaceOnUse"><path d="M28 0L0 0 0 28" className="grid-line"/></pattern></defs><rect width="900" height="510" rx="16" className="map-bg"/><rect width="900" height="510" rx="16" fill="url(#grid)"/><path d="M126 260H725" className="robot-path"/><path d="M450 180V222M450 298V340" className="robot-path faint"/>{route.slice(1).map((node,i)=><line key={`${selectedExperiment}-${i}`} x1={route[i].point[0]} y1={route[i].point[1]} x2={node.point[0]} y2={node.point[1]} className={`route-line ${node.status}`}/>)}
   <g className={`station route-device ${routeStatus("liquid-01")??"dimmed"}`} onClick={()=>setSelected(devices[1])}><rect x="55" y="78" width="220" height="135" rx="14"/><text x="75" y="110">液体处理设备</text><text x="75" y="140" className="machine-label">Liquid Handler 01</text><circle cx="245" cy="103" r="6" className="dot-idle"/><rect x="82" y="160" width="64" height="30" rx="5" className="plate"/><text x="91" y="180" className="plate-label">plate-001</text></g>
   <g className={`station alarm-station route-device ${routeStatus("reader-01")??"dimmed"}`} onClick={()=>setSelected(devices[2])}><rect x="625" y="72" width="220" height="145" rx="14"/><text x="647" y="105">检测设备</text><text x="647" y="136" className="machine-label">Plate Reader 01</text><circle cx="815" cy="100" r="6" className="dot-alarm"/><path d="M760 160l10-18 10 18z" className="alarm-symbol"/></g>
   <g className={`station route-device ${routeStatus("centrifuge-01")??"dimmed"}`} onClick={()=>setSelected(devices[4])}><rect x="350" y="62" width="200" height="118" rx="14"/><text x="372" y="96">离心设备</text><text x="372" y="126" className="machine-label">Centrifuge 01 · Ready</text><circle cx="522" cy="91" r="6" className="dot-idle"/><circle cx="450" cy="150" r="16" className="device-symbol"/></g>
   <g className={`station multi-station route-device ${routeStatus("incubator-01")??"dimmed"}`} onClick={()=>setSelected(devices[3])}><rect x="50" y="330" width="220" height="120" rx="14"/><text x="72" y="363">恒温培养设备</text><text x="72" y="390" className="machine-label">Incubator 01 · 3 / 8 槽位</text><text x="72" y="416" className="multi-label">EXP-014 · EXP-021 · EXP-023</text><circle cx="240" cy="357" r="6" className="dot-running"/></g><g className="station route-device dimmed"><rect x="625" y="330" width="220" height="120" rx="14"/><text x="647" y="363">机器人充电设备</text><text x="647" y="392" className="machine-label">Dock 01 · Ready</text></g>
   <g className={`station route-device ${routeStatus("imager-01")??"dimmed"}`} onClick={()=>setSelected(devices[5])}><rect x="350" y="340" width="200" height="110" rx="14"/><text x="372" y="373">显微成像设备</text><text x="372" y="402" className="machine-label">Imager 01 · EXP-021</text><text x="372" y="428" className="multi-label">扫描视野 4 / 12</text><circle cx="522" cy="368" r="6" className="dot-running"/></g>
   <g className={`robot route-robot ${routeStatus("robot-01")??"dimmed"}`} transform={`translate(${robotX*8.3},260)`} onClick={()=>setSelected(devices[0])}><circle r="28"/><circle r="20" className="robot-inner"/><path d="M-10-3h20M-7 7h14"/><circle cx="-9" cy="-10" r="2.5"/><circle cx="9" cy="-10" r="2.5"/><text x="0" y="48" textAnchor="middle">Robot 01</text></g></svg><div className="route-summary"><b>{selectedExperiment}</b><span><i className="done"/>已完成</span><span><i className="current"/>当前</span><span><i className="upcoming"/>后续</span></div><div className="zoom-controls"><button onClick={()=>setZoom(z=>Math.max(.7,+(z-.1).toFixed(1)))} aria-label="缩小地图"><Minus size={16}/></button><button className="zoom-value" onClick={()=>setZoom(1)} title="恢复 100%">{Math.round(zoom*100)}%</button><button onClick={()=>setZoom(z=>Math.min(1.5,+(z+.1).toFixed(1)))} aria-label="放大地图"><Plus size={16}/></button></div><div className="map-toast"><Bot size={16}/><span><b>Robot 01</b> 搬运 plate-001</span><em>{Math.round(robotX)}%</em></div></div></div></div>
  </section>
  <div className="floating-actions">
   <Sheet><SheetTrigger asChild><button><Server size={17}/><span>设备</span><b>6</b></button></SheetTrigger><SheetContent className="twin-sheet"><SheetHeader><SheetTitle>设备状态</SheetTitle><SheetDescription>选择设备查看实时资源与实验占用</SheetDescription></SheetHeader><div className="device-list">{devices.map(d=><button key={d.id} className={`device-card ${selected.id===d.id?"selected":""}`} onClick={()=>setSelected(d)}><div className="device-title"><span className="device-icon">{d.id.startsWith("robot")?<Bot/>:d.id.startsWith("liquid")?<TestTube2/>:<Gauge/>}</span><div><b>{d.name}</b><small>{d.type}</small></div><Status state={d.state}/></div><p>{d.action}</p><div className="capacity-line"><span>{d.mode}</span><b>{d.workloads.length} / {d.capacity} 占用</b></div>{d.progress>0&&<div className="progress"><span style={{width:`${d.progress}%`}}/></div>}</button>)}</div><div className="detail-card"><div className="detail-head"><div><small>当前选择</small><h3>{selected.name}</h3></div><Status state={selected.state}/></div><p>{selected.detail}</p><dl><div><dt>并发模式</dt><dd>{selected.mode}</dd></div><div><dt>资源占用</dt><dd>{selected.workloads.length} / {selected.capacity}</dd></div><div><dt>Feature</dt><dd>{selected.type}</dd></div></dl>{selected.state==="异常"&&<div className="recovery-note"><AlertTriangle size={16}/><div><b>等待设备侧恢复</b><span>设备人员现场处理 → 设备执行自检 → SiLA 2 上报正常状态 → 平台重新排程</span></div></div>}{selected.workloads.length>0&&<div className="workloads"><small>设备内运行实验</small>{selected.workloads.map(w=><div className="workload" key={`${w.experiment}-${w.slot}`}><div><b>{w.experiment}</b><span>{w.sample} · {w.slot}</span></div><em>{w.state} {w.progress}%</em></div>)}</div>}<button className="secondary"><RotateCcw size={15}/> 查看事件历史</button></div></SheetContent></Sheet>
  </div>
  <Sheet><SheetTrigger asChild><button className="timeline-trigger"><ListTree size={17}/><span>实验与事件</span><b>{selectedExperiment.replace("EXP-2026-", "EXP-")}</b></button></SheetTrigger><SheetContent side="bottom" className="operations-sheet"><SheetHeader><SheetTitle>实验运行中心</SheetTitle><SheetDescription>点击实验，在地图中查看所需设备、执行顺序和当前状态</SheetDescription></SheetHeader><section className="bottom-grid"><div className="run-panel"><div className="panel-heading"><div><h2>并行实验执行链</h2><p>3 个实验正在共享设备资源</p></div><span className="eta">选择实验查看路径</span></div><div className="experiment-runs">{experimentRuns.map(run=><SheetClose asChild key={run.id}><button className={`experiment-run ${selectedExperiment===run.id?"selected":""}`} onClick={()=>setSelectedExperiment(run.id as keyof typeof experimentRoutes)}><div className="run-identity"><b>{run.id}</b><span>{run.name}</span><small>{run.device} · ETA {run.eta}</small></div><div className="mini-steps">{run.steps.map((s,i)=><div key={s} className={`mini-step ${i<run.active?"done":i===run.active?"active":""}`} title={s}><i>{i<run.active?"✓":i+1}</i><span>{s}</span>{i<run.steps.length-1&&<b/>}</div>)}</div></button></SheetClose>)}</div></div><div className="event-panel"><div className="panel-heading"><div><h2>实时事件</h2><p>命令、状态与异常回流</p></div></div><div className="events">{events.map((e,i)=><div className={`event ${e[3]}`} key={`${e[0]}-${i}`}><time>{e[0]}</time><b>{e[1]}</b><span>{e[2]}</span></div>)}</div></div></section></SheetContent></Sheet>
 </main>
}
